site_name: fhir-research
site_dir: build/site
repo_url: https://github.com/wuxxin/fhir-research
theme:
  name: material
nav:
  - README.md
  - fhir-profiles.md

markdown_extensions:
  - smarty
  - toc:
      permalink: "#"
  - pymdownx.magiclink
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
