# This workflow will install Python dependencies, run tests and lint with a single version of Python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: make buildenv
    - name: Test
      run: make test
    - name: Docs
      run: make docs
    - name: Lint
      run: make lint
    - name: upload test artifact
      uses: actions/upload-artifact@v4
      with:
        name: test-artifact
        path: build/test
    - name: Upload github pages artifact
      uses: actions/upload-pages-artifact@v3
      id: pages-deployment
      with:
        path: build/site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        id: pages-deployment
